require conf/machine/include/ast2700-sdk.inc
require conf/machine/include/ast2700-a1.inc
require conf/machine/include/ast-ssp.inc
require conf/machine/include/ast-tsp.inc
require conf/machine/include/obmc-bsp-common.inc
require conf/machine/include/intel-pfr.inc

# Overwrite flash layout

#FLASH_SIZE = "131072"
FLASH_CALIPTRA_SIZE:flash-131072 = "128"
FLASH_BMCU_SIZE:flash-131072 = "896"
FLASH_UBOOT_OFFSET:flash-131072 = "0"
FLASH_UBOOT_ENV_OFFSET:flash-131072 = "4096"
FLASH_KERNEL_OFFSET:flash-131072 = "4224"
FLASH_ROFS_OFFSET:flash-131072 = "15488"
FLASH_RWFS_OFFSET:flash-131072 = "100352"

# 256MB flash overrides (pfr-256)
FLASH_CALIPTRA_SIZE:flash-262144 = "128"
FLASH_BMCU_SIZE:flash-262144 = "896"
FLASH_UBOOT_OFFSET:flash-262144 = "0"
FLASH_UBOOT_ENV_OFFSET:flash-262144 = "4096"
FLASH_KERNEL_OFFSET:flash-262144 = "4224"
FLASH_ROFS_OFFSET:flash-262144 = "15488"
FLASH_RWFS_OFFSET:flash-262144 = "72832"

# PFR settings
PFR_IMAGE_SIZE = "262144"
# 0x04000000
PFM_OFFSET_PAGE = "65536"
# 0x04220000
RC_IMAGE_PAGE = "67712"
PFR_MANIFEST = "pfr_manifest_ast2700_dcscm.json"
# 1 = SHA256
# 2 = SHA384
# 3 = LMS384
# 4 = LMS256
PFR_SHA = "2"

# CALIPTRA Settings
CALIPTRA_FW_BINARY = "caliptra-fw.bin"
# CALIPTRA Manifest
CALIPTRA_MANIFEST_CONFIG ??= "ast2700a1-default-ecc-manifest.toml"

# BootMCU Build Settings
# SoC First Mutable Code (FMC) image
FMC_IMAGE_ENABLE = "1"
BOOTMCU_FMC_BINARY = "ast2700-mcu-runtime.bin"
ZEPHYR_BOARD_BOOTMCU ?= "ast2700_evb/ast2700_a1/bootmcu"

# U-Boot Build Settings
UBOOT_MACHINE = "evb-ast2700_defconfig"
UBOOT_DEVICETREE = "ast2700-dcscm"

# SSP Settings
ZEPHYR_BOARD_SSP ?= "ast2700_evb/ast2700_a1/ssp_tsp"

# TSP Settings
ZEPHYR_BOARD_TSP ?= "ast2700_evb/ast2700_a1/tsp"

# Kernel Build Settings
KBUILD_DEFCONFIG = "aspeed_g7_defconfig"

MACHINE_FEATURES += "\
        obmc-phosphor-fan-mgmt \
        obmc-phosphor-chassis-mgmt \
        obmc-phosphor-flash-mgmt \
        obmc-host-ipmi \
        obmc-host-state-mgmt \
        obmc-chassis-state-mgmt \
        obmc-bmc-state-mgmt \
        "

PREFERRED_PROVIDER_virtual/obmc-system-mgmt = "packagegroup-aspeed-obmc"
PREFERRED_PROVIDER_virtual/obmc-host-ipmi-hw = "phosphor-ipmi-kcs"
PREFERRED_PROVIDER_virtual/phosphor-led-manager-config-native = "dcscm-2700-led-manager-config-native"
VIRTUAL-RUNTIME_obmc-host-state-manager ?= "x86-power-control"
VIRTUAL-RUNTIME_obmc-chassis-state-manager ?= "x86-power-control"

EXTRA_IMAGEDEPENDS:append = " \
    aspeed-image-recoveryuart \
    "

MACHINEOVERRIDES =. "intel-ast2700:"