#!/bin/bash

NVMP=/tmp/.rwfs
SOMP=/var/sofs

clean_var_volatile_tmp() {
    rm -rf $NVMP/.overlay/var/volatile/tmp/* || :
}

do_sync() {
    # Ensure the file responsible for monotonicity between boots is
    # refreshed. Firmware updates are completed by assertion of the
    # BMC reset input. This prevents timesyncd from gracefully
    # updating this file.
    touch /var/lib/systemd/timesync/clock

    rsync -a --inplace --partial --delete \
    --include='/var/log/nm_events/' \
    --include='/var/log/phosphor-post-code-manager/***' \
    --include='/var/log/obmc-console/***' \
    --exclude='/var/log/**' \
    --exclude='**/var/volatile/tmp/**' \
    /tmp/.overlay/ $NVMP/.overlay

    sync $NVMP/.overlay
}

stop_nv() {
    history -a
    do_sync
    mount -o remount,ro $NVMP
    mount -o remount,ro $SOMP
    exit 0
}

# register cleanup function
trap stop_nv SIGINT
trap stop_nv SIGTERM
trap stop_nv EXIT

# make sure the mount points are RW
mount -o remount,rw $NVMP
mount -o remount,rw $SOMP

clean_var_volatile_tmp

# Run rsync periodically to sync the overlay to NV storage
while true; do
    do_sync
    sleep 10
done
